# Generated by Django 4.2 on 2024-12-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_reschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedule',
            name='new_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
