# Generated by Django 4.2 on 2025-01-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_notification_notificationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
