# Generated by Django 4.2 on 2025-01-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_destination_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentupdate',
            name='from_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipmentupdate',
            name='to_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
